/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.colegioamigosdedonbosco.formularios;

import java.awt.Color;

/**
 *
 * @author elaniin
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        mostrarPanel("bienvenida");
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    private void mostrarPanel(String panel) {
        pnlPrestamos.setVisible(panel.equals("prestamos"));
        pnlEjemplares.setVisible(panel.equals("ejemplares"));
        pnlCategorias.setVisible(panel.equals("categorias"));
        pnlUsuarios.setVisible(panel.equals("usuarios"));
        pnlRoles.setVisible(panel.equals("roles"));
        pnlConfiguracion.setVisible(panel.equals("configuracion"));
        pnlBienvenida.setVisible(panel.equals("bienvenida"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnEjemplares = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlBienvenida = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlPrestamos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlEjemplares = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlConfiguracion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlRoles = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlUsuarios = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlCategorias = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 204, 51));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setName("PantallaPrincipal"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setBackground(new java.awt.Color(199, 0, 57));
        btnCerrarSesion.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 11)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 120, 50));

        btnCategorias.setBackground(new java.awt.Color(55, 60, 86));
        btnCategorias.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 11)); // NOI18N
        btnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnCategorias.setText("CATEGORIAS");
        btnCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 50));

        btnRoles.setBackground(new java.awt.Color(55, 60, 86));
        btnRoles.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 11)); // NOI18N
        btnRoles.setForeground(new java.awt.Color(255, 255, 255));
        btnRoles.setText("ROLES");
        btnRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 120, 50));

        btnConfiguracion.setBackground(new java.awt.Color(55, 60, 86));
        btnConfiguracion.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 11)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setText("CONFIGURACIÓN");
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 120, 50));

        btnPrestamos.setBackground(new java.awt.Color(55, 60, 86));
        btnPrestamos.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 11)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamos.setText("PRESTAMOS");
        btnPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 50));

        btnUsuarios.setBackground(new java.awt.Color(55, 60, 86));
        btnUsuarios.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 11)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 120, 50));

        btnEjemplares.setBackground(new java.awt.Color(55, 60, 86));
        btnEjemplares.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 11)); // NOI18N
        btnEjemplares.setForeground(new java.awt.Color(255, 255, 255));
        btnEjemplares.setText("EJEMPLARES");
        btnEjemplares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemplaresActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, 50));

        jLabel1.setBackground(new java.awt.Color(55, 60, 86));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 520));

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CADB");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 80));

        jLabel2.setBackground(new java.awt.Color(68, 117, 245));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        pnlBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        pnlBienvenida.setMaximumSize(new java.awt.Dimension(880, 600));
        pnlBienvenida.setMinimumSize(new java.awt.Dimension(880, 600));
        pnlBienvenida.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlBienvenidaComponentShown(evt);
            }
        });
        pnlBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Selecciona una opcion del menu lateral");
        pnlBienvenida.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        jLabel11.setText("¡Bienvenido!");
        pnlBienvenida.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        getContentPane().add(pnlBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 880, 600));

        pnlPrestamos.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrestamos.setMaximumSize(new java.awt.Dimension(880, 600));
        pnlPrestamos.setMinimumSize(new java.awt.Dimension(880, 600));
        pnlPrestamos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlPrestamosComponentShown(evt);
            }
        });
        pnlPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel9.setText("Prestamos");
        pnlPrestamos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(pnlPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 880, 600));

        pnlEjemplares.setBackground(new java.awt.Color(255, 255, 255));
        pnlEjemplares.setMaximumSize(new java.awt.Dimension(880, 600));
        pnlEjemplares.setMinimumSize(new java.awt.Dimension(880, 600));
        pnlEjemplares.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel4.setText("Ejemplares");
        pnlEjemplares.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(pnlEjemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 880, 600));

        pnlConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        pnlConfiguracion.setMaximumSize(new java.awt.Dimension(880, 600));
        pnlConfiguracion.setMinimumSize(new java.awt.Dimension(880, 600));
        pnlConfiguracion.setPreferredSize(new java.awt.Dimension(880, 600));
        pnlConfiguracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel5.setText("Configuración");
        pnlConfiguracion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(pnlConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 880, 600));

        pnlRoles.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoles.setMaximumSize(new java.awt.Dimension(880, 600));
        pnlRoles.setMinimumSize(new java.awt.Dimension(880, 600));
        pnlRoles.setPreferredSize(new java.awt.Dimension(880, 600));
        pnlRoles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel6.setText("Roles");
        pnlRoles.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(pnlRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 880, 600));

        pnlUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuarios.setMaximumSize(new java.awt.Dimension(880, 600));
        pnlUsuarios.setMinimumSize(new java.awt.Dimension(880, 600));
        pnlUsuarios.setPreferredSize(new java.awt.Dimension(880, 600));
        pnlUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel7.setText("Usuarios");
        pnlUsuarios.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(pnlUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 880, 600));

        pnlCategorias.setBackground(new java.awt.Color(255, 255, 255));
        pnlCategorias.setMaximumSize(new java.awt.Dimension(880, 600));
        pnlCategorias.setMinimumSize(new java.awt.Dimension(880, 600));
        pnlCategorias.setPreferredSize(new java.awt.Dimension(880, 600));
        pnlCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel8.setText("Categorias");
        pnlCategorias.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(pnlCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 880, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        new IniciarSesion().setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemplaresActionPerformed
        this.mostrarPanel("ejemplares");
    }//GEN-LAST:event_btnEjemplaresActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        this.mostrarPanel("categorias");
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        this.mostrarPanel("usuarios");
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        this.mostrarPanel("roles");
    }//GEN-LAST:event_btnRolesActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        this.mostrarPanel("configuracion");
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        this.mostrarPanel("prestamos");
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void pnlPrestamosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlPrestamosComponentShown
        System.out.println("Se cargo el panel de prestamos");
    }//GEN-LAST:event_pnlPrestamosComponentShown

    private void pnlBienvenidaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlBienvenidaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBienvenidaComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnEjemplares;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnRoles;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlBienvenida;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlConfiguracion;
    private javax.swing.JPanel pnlEjemplares;
    private javax.swing.JPanel pnlPrestamos;
    private javax.swing.JPanel pnlRoles;
    private javax.swing.JPanel pnlUsuarios;
    // End of variables declaration//GEN-END:variables
}
